repos:

  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version
    rev: 0.7.13  # so'nggi versiyani tekshirib, yangilab boring
    hooks:
      # Update the uv lockfile
      - id: uv-lock

  # - repo: https://github.com/astral-sh/ruff-pre-commit
  #   rev: v0.12.0  # so'nggi versiyani tekshirib, yangilab boring
  #   hooks:
  #     # Run The linter
  #     - id: ruff-check
  #       args: ["--fix"]  # avtomatik tuzatish (ixtiyoriy)
  #     - id: ruff-format
