"""task due_date remove default

Revision ID: 44a90edc24f8
Revises: a7f562f9e933
Create Date: 2025-07-19 18:47:03.807463

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '44a90edc24f8'
down_revision: Union[str, Sequence[str], None] = 'a7f562f9e933'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
