"""feat: change models

Revision ID: 6360bc53df9c
Revises: e0a6c45753bb
Create Date: 2025-09-09 15:37:05.442958

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6360bc53df9c"
down_revision: Union[str, Sequence[str], None] = "e0a6c45753bb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("is_deleted", sa.Boolean(), nullable=False))
    op.drop_column("users", "is_delated")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("is_delated", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_column("users", "is_deleted")
    # ### end Alembic commands ###
