"""initial

Revision ID: 781b9405b06d
Revises: 903abd13774f
Create Date: 2025-07-21 02:09:10.716058

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '781b9405b06d'
down_revision: Union[str, Sequence[str], None] = '903abd13774f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
