"""initial

Revision ID: 903abd13774f
Revises: a00ec8f32f87
Create Date: 2025-07-21 02:04:17.332820

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '903abd13774f'
down_revision: Union[str, Sequence[str], None] = 'a00ec8f32f87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
