"""initial

Revision ID: 9b7861c05ead
Revises: 781b9405b06d
Create Date: 2025-07-21 02:11:41.239899

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '9b7861c05ead'
down_revision: Union[str, Sequence[str], None] = '781b9405b06d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
