"""initial

Revision ID: a00ec8f32f87
Revises: 44a90edc24f8
Create Date: 2025-07-21 01:55:29.518767

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'a00ec8f32f87'
down_revision: Union[str, Sequence[str], None] = '44a90edc24f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
