"""add: user Role

Revision ID: a7f562f9e933
Revises: 8288b7e1197e
Create Date: 2025-07-18 15:47:02.626678

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'a7f562f9e933'
down_revision: Union[str, Sequence[str], None] = '8288b7e1197e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
