"""add: task relationships

Revision ID: e108764115b0
Revises: f4a43ff2f5de
Create Date: 2025-07-21 10:58:40.014453

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'e108764115b0'
down_revision: Union[str, Sequence[str], None] = 'f4a43ff2f5de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
