"""feat: models change

Revision ID: eeb25e013794
Revises: 537a52228d2f
Create Date: 2025-09-04 16:21:57.037971

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eeb25e013794"
down_revision: Union[str, Sequence[str], None] = "537a52228d2f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("tasks_status_id_fkey"), "tasks", type_="foreignkey")
    op.drop_column("tasks", "status_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks",
        sa.Column("status_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        op.f("tasks_status_id_fkey"),
        "tasks",
        "statuses",
        ["status_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
