"""add: task relationships

Revision ID: f4a43ff2f5de
Revises: f766b01d03d1
Create Date: 2025-07-21 10:52:09.411889

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'f4a43ff2f5de'
down_revision: Union[str, Sequence[str], None] = 'f766b01d03d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
