"""add: task relationships

Revision ID: f766b01d03d1
Revises: 9b7861c05ead
Create Date: 2025-07-21 10:49:25.226389

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'f766b01d03d1'
down_revision: Union[str, Sequence[str], None] = '9b7861c05ead'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
