"""add: models

Revision ID: fcbb214294b4
Revises: b91f64e71518
Create Date: 2025-07-17 20:14:34.958899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fcbb214294b4'
down_revision: Union[str, Sequence[str], None] = 'b91f64e71518'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_members', sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('project_members', 'joinedat')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_members', sa.Column('joinedat', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('project_members', 'joined_at')
    # ### end Alembic commands ###
